(DEFUN MUTATION-TEST (X Y)
  "Función que abusa de los efectos secundarios."
  (INCF X)
  (SETF Y (* X 2))
  (FORMAT T "Resultado: ~A" (+ X Y)))
(DEFUN DATA-VALID-P (DATA)
  "Es un predicado, devolver NIL es normal."
  (WHEN (> DATA 0) T))
(DEFUN TEST-P (X) "Es predicado." NIL)
(DEFUN CALCULATE-PROCESS (DATA) "Docstring presente." NIL)
(DEFUN PROCESADOR-A-P (DATA CONFIG MODE TARGET LOG-LEVEL DEBUG-P)
  "Llama al motor B."
  (MOTOR-B DATA))
(DEFUN MOTOR-B (X)
  "Cierra ciclo con A y usa C."
  (MODULO-C X)
  (PROCESADOR-A-P X NIL NIL NIL NIL NIL))
(DEFUN MODULO-C (X) "No llama a nadie." (FORMAT T "Fin de cadena: ~A" X))
(DEFUN FUNCION-D (X) (MODULO-C X))
(DEFUN PROCESAR-TELEMETRIA-SEGURA (LECTURAS)
  "Filtra lecturas entre 0 y 100, aplicando un factor de correccion de 0.9 
   a valores superiores a 80. Implementacion optimizada para baja asignacion 
   de memoria y cumplimiento de normas NASA JPL."
  (LET ((LIMITE-SUPERIOR 100)
        (LIMITE-INFERIOR 0)
        (UMBRAL-CORRECCION 80)
        (FACTOR-ESCALA 0.9))
    (LOOP FOR X IN LECTURAS
          WHEN (AND (>= X LIMITE-INFERIOR) (<= X LIMITE-SUPERIOR))
          COLLECT (IF (> X UMBRAL-CORRECCION)
                      (* X FACTOR-ESCALA)
                      X))))


;; Generated by IISCV dump-source-code
;; Timestamp: 3979401818
