;; Function definitions
;; Generated by IISCV
(DEFUN MUTATION-TEST (X Y)
  "Función que abusa de los efectos secundarios."
  (INCF X)
  (SETF Y (* X 2))
  (FORMAT T "Resultado: ~A" (+ X Y)))
(DEFUN DATA-VALID-P (DATA)
  "Es un predicado, devolver NIL es normal."
  (WHEN (> DATA 0) T))
(DEFUN TEST-P (X) "Es predicado." NIL)
(DEFUN CALCULATE-PROCESS (DATA) "Docstring presente." NIL)
(DEFUN PROCESADOR-A-P (DATA CONFIG MODE TARGET LOG-LEVEL DEBUG-P)
  "Llama al motor B."
  (MOTOR-B DATA))
(DEFUN MOTOR-B (X)
  "Cierra ciclo con A y usa C."
  (MODULO-C X)
  (PROCESADOR-A-P X NIL NIL NIL NIL NIL))
(DEFUN MODULO-C (X) "No llama a nadie." (FORMAT T "Fin de cadena: ~A" X))
(DEFUN FUNCION-D (X) (MODULO-C X))
