;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; 6. FILE DUMP & RECONSTRUCTION (RESTORED)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(in-package :iiscv)


;; hacerlo relativo al directorio de trabajo o pasar la ruta como argumento
(defun dump-source-code (&optional (output-dir #p"output_src/"))
  "Dumps all source code from human commits into files. Extracts only the latest versions of each symbol to avoid duplication."

  (let ((processed-symbols (make-hash-table :test 'equal)) 
        (final-forms '())) 
    
    
    (loop for human-vertex in (cl-graph:topological-sort *human-history-graph*)
          for human-data = (cl-graph:element human-vertex)
          for atomic-uuids = (getf human-data :atomic-uuids)
          do (loop for atomic-uuid in atomic-uuids
                  do (let* ((atomic-vertex (find-vertex-by-uuid *atomic-history-graph* atomic-uuid))
                           (atomic-data (cl-graph:element atomic-vertex))
                           (form (getf atomic-data :source-form))
                           (symbol-name (getf atomic-data :symbol-name)))
                       
    
                       (when (and symbol-name
                                  (listp form))
                         
    
                         (unless (gethash symbol-name processed-symbols)
                           (push form final-forms)
                           (setf (gethash symbol-name processed-symbols) t))))))
    
    
    (ensure-directories-exist output-dir)
    
    
    (with-open-file (stream (merge-pathnames "dump.lisp" output-dir)
                           :direction :output
                           :if-exists :supersede)
      (dolist (form (reverse final-forms))
        (format stream "~S~%" form))
      (format stream "~%~%;; Generated by IISCV dump-source-code~%")
      (format stream ";; Timestamp: ~A~%" (get-universal-time)))
    
    (format t "Dump source: ~A~%" (merge-pathnames "dump.lisp" output-dir))
    (length final-forms)))



;; hacerlo relativo al directorio de trabajo o pasar la ruta como argumento
(defun dump-source-code-by-commit-type (&optional (output-dir #p"output_src/"))
  "Dumps the source code grouped by the type of commit recorded."

  (let ((processed-symbols (make-hash-table :test 'equal))
        (forms-by-commit-type (make-hash-table :test 'equal))) ; commit-type -> lista de formas
    ; Loop through human commits and group by commit type
    (loop for human-vertex in (cl-graph:topological-sort *human-history-graph*)
          for human-data = (cl-graph:element human-vertex)
          for atomic-uuids = (getf human-data :atomic-uuids)
          do (loop for atomic-uuid in atomic-uuids
                  do (let* ((atomic-vertex (find-vertex-by-uuid *atomic-history-graph* atomic-uuid))
                           (atomic-data (cl-graph:element atomic-vertex))
                           (form (getf atomic-data :source-form))
                           (symbol-name (getf atomic-data :symbol-name)))
                       
		       
                       (when (and symbol-name
                                  (listp form))
                         
                         
                         (let ((commit-type (get-commit-type form)))
                           (when commit-type
                             
                             (unless (gethash symbol-name processed-symbols)
                               (push form (gethash commit-type forms-by-commit-type))
                               (setf (gethash symbol-name processed-symbols) t))))))))
    
    
    (ensure-directories-exist output-dir)
    
    
    (with-open-file (main-stream (merge-pathnames "main.lisp" output-dir)
                                :direction :output
                                :if-exists :supersede)
      (format main-stream ";; Generated by IISCV dump-source-code-by-commit-type~%")
      (format main-stream ";; Timestamp: ~A~%~%" (get-universal-time))
      (loop for commit-type being the hash-keys of forms-by-commit-type
            for filename = (case commit-type
                             (function "functions.lisp")
                             (variable "variables.lisp")
                             (type "types.lisp")
                             (slot-change "slot-changes.lisp")
                             (dependency "dependencies.lisp")
                             (t (format nil "~a.lisp" commit-type)))
            do (format main-stream "(load \"~A\")~%" filename)))
    
    (loop for commit-type being the hash-keys of forms-by-commit-type
          for forms being the hash-values of forms-by-commit-type
          for filename = (case commit-type
                           (function "functions.lisp")
                           (variable "variables.lisp")
                           (type "types.lisp")
                           (slot-change "slot-changes.lisp")
                           (dependency "dependencies.lisp")
                           (t (format nil "~a.lisp" commit-type)))
          when forms
          do (with-open-file (stream (merge-pathnames filename output-dir)
                                   :direction :output
                                   :if-exists :supersede)
               (format stream ";; ~A definitions~%" (string-capitalize (string commit-type)))
               (format stream ";; Generated by IISCV~%")
               (dolist (form (reverse forms))
                 (format stream "~S~%" form))))
    
    (format t "Source code dumped by commit type in: ~A~%" output-dir)))

